### PR TITLE
Composer post install script

### LINKED ISSUE #526: upgrade dot-mail to 5.1
### Bug Report

dot-mail must be 5.1

### PR DESCRIPTION
**Pull request by marioradu05**

### CODE REVIEW

**Review by pinclau — APPROVED** [review]

File: bin/composer-post-install-script.php [hunk 1]
```diff
@@ -0,0 +1,51 @@
...
+
+function isDevModeEnabled(): bool
+{
+    return file_exists('config/autoload/development.local.php');
+}
+
+// when adding files to the below array the `source` and `destination` must be relative to the project root folder
+// the `environment` key will indicate when the file should be copied,
+// if the value is `production` the file will be copied on both production and local environments,
+// if the value is `local` the file will be copied only on local environments
```
Comment (alexmerlin) [inline bin/composer-post-install-script.php]: Not sure if `local` is the best term to use here. Maybe `development`? 🤔 

Also, maybe we could use `environment` as an array where we specify exactly the environments where a file should be copied? Example:
```php
'environment' => ['env1', 'env2'],
```
Thoughts?

Comment (marioradu05) [reply bin/composer-post-install-script.php]: @alexmerlin yes, `development` sound better then `local`,
I've refactored the script based on your suggestions.

**Review by alexmerlin — APPROVED** [review]

**Review by arhimede — APPROVED** [review]
