### PR TITLE
moved email message to & cc names to config file

### LINKED ISSUE #537: remove dotkernel string from source code
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | x.y.z

#### Summary

check all  files and move everywhere you see the string "dotkernel' to config file

### PR DESCRIPTION
**Pull request by Jurj-Bogdan**
moved the hardcoded "Dotkernel Team" string to a config file.

### CODE REVIEW

File: config/autoload/local.php.dist [hunk 1]
```diff
@@ -47,10 +47,11 @@ return [
     'contact'             => [
         'notification_receivers' => [],
         'message_receivers'      => [
```
Comment (arhimede) [inline config/autoload/local.php.dist]: I do not like the string 'receiver'.
In email world, the standard string is 'recipients'
At least for me , 'receiver' is confusing
@alexmerlin your opionion ?

Comment (Jurj-Bogdan) [reply config/autoload/local.php.dist]: Another idea might be dropping the "contact" key from `local.php` altogether, as the only part it's used by default is the `sendContactMail` function in `MessageService.php`.

 That function already uses the config file from dot-mail (mail.global.php) for the "addFrom" method, and that has the `to` and `cc` keys available as well.

Comment (arhimede) [reply config/autoload/local.php.dist]: > Another idea might be dropping the "contact" key from `local.php` altogether, as the only part it's used by default is the `sendContactMail` function in `MessageService.php`.
> 
> That function already uses the config file from dot-mail (mail.global.php) for the "addFrom" method, and that has the `to` and `cc` keys available as well.

Let' discuss tomorrow 
as i do not like either the line from MessageService.php 
$this->config['contact']['message_receivers']['to'],
$this->config['contact']['message_receivers']['cc'],

**Review by arhimede — COMMENTED** [review]
Refactor the below key from local.php.dist
- remove unused key notification_receivers
- use the variable names:  recipient, sender
- add a variable for subject and BCC 
- for mandatory fields use fallback from maip config ( sender, recipient, subject )

`     'contact'               => [
        'notification_receivers' => [],
        'message_receivers'      => [
            'to' => [
                'tech@apidemia.com',
            ],
            'cc' => [
                'tech@apidemia.com',
            ],
        ],
    ],`

**Comment by arhimede** [comment]
contact form sender, in general, is platform sender configured in mail.php config file 
in code, the email that create the form must be in `Reply-to` field

File: config/autoload/local.php.dist [hunk 2]
```diff
@@ -45,15 +45,22 @@ return [
         ],
     ],
     'contact'             => [
-        'notification_receivers' => [],
-        'message_receivers'      => [
+        'subject'            => 'Dotkernel Contact',
+        'message_sender'     => [
+            'name'    => '',
```
Comment (arhimede) [inline config/autoload/local.php.dist]: better a variable name like 
`from_name`

File: config/autoload/local.php.dist [hunk 3]
```diff
@@ -45,15 +45,22 @@ return [
...
+            'address' => '',
```
Comment (arhimede) [inline config/autoload/local.php.dist]: better a variable name like 
`from_email`

**Comment by arhimede** [comment]
why there are 19 files commited ?

**Comment by alexmerlin** [comment]
> why there are 19 files commited ?

Because @Jurj-Bogdan must have merged the latest changes from `5.0` into this branch.
It's just `GitHub` seeing the merged files as new ones compared to when the branch was created.
When the PR is merged, `GitHub` will see that they already exist on `5.0` so it won't touch them.

**Comment by Jurj-Bogdan** [comment]
> why there are 19 files commited ?

i have rebased the `issue537` branch to make sure no conflicts exist with the `5.0` branch which was updated in the meantime

**Comment by Jurj-Bogdan** [comment]
yup, i rebased this branch to make sure no conflicts exist with the default branch which was updated while this PR was open

**Review by arhimede — APPROVED** [review]
@alexmerlin please merge this one
