### PR TITLE
Issue #533: Fixed user is not defined error

### LINKED ISSUE #533: crash remember-me
### Bug Report

|    Q        |   A
|------------ | ------
| Version(s)  | 5.1.0

#### Summary

remember-me function is crashing 

#### Current behavior

error 
`"priority":3,"priorityName":"ERR","message":"[Semantical Error] line 0, col 166 near 'user.status !=': Error: 'user' is not defined.","extra":{"\u0000*\u0000message":"[Semantical Error] line 0, col 166 near 'user.status !=': Error: 'user' is not defined."`

#### How to reproduce

login with the remember-me checkbox checked

#### Expected behavior

no errors

### PR DESCRIPTION
**Pull request by SergiuBota1**

### CODE REVIEW

**Review by arhimede — APPROVED** [review]

File: src/User/src/Repository/UserRepository.php [hunk 1]
```diff
@@ -34,6 +34,7 @@ public function findByUuid(string $uuid): ?User
         $qb
             ->select('user')
             ->from(User::class, 'user')
+            ->join('user_remember_me.user', 'user')
```
Comment (alexmerlin) [inline src/User/src/Repository/UserRepository.php]:
```suggestion
```
`user_remember_me` is NOT used in this query.

**Review by alexmerlin — CHANGES_REQUESTED** [review]

**Review by alexmerlin — APPROVED** [review]

**Comment by alexmerlin** [comment]
@SergiuBota1 The missing signature issue also needs to be fixed before merging this PR.
